Credit Risk & Rating Analysis

Import Libraries

In [8]:
import pandas as pd
import numpy as np

Load Dataset

In [11]:
data = (r'C:\Users\navee\OneDrive\Desktop\HR ANALYTICS\Credit Risk & Rating Analysis\credit_risk_raw.csv')
df = pd.read_csv(data)

Data Profiling

In [19]:
print('Top Five Rows of Dataset')
df.head(5)

Top Five Rows of Dataset

,customer_id,age,income,employment_status,loan_amount,loan_type,credit_score,missed_payments,last_payment_date,account_status,region
0,CUST1000,58.0,46627,Student,401591.0,Personal,772,3,2026-02-01 06:39:58.479418,Default,North
1,CUST1001,48.0,78251,Student,424494.0,Home,697,2,2026-03-08 06:39:58.479456,Delayed,West
2,CUST1002,34.0,51831,Salaried,555074.0,Personal,644,5,2026-03-12 06:39:58.479461,Delayed,West
3,CUST1003,27.0,23009,Self-employed,565303.0,Business,798,4,2026-02-14 06:39:58.479464,Default,South
4,CUST1004,40.0,136595,Business,567196.0,Personal,634,2,2026-03-02 06:39:58.479467,Delayed,North

In [30]:
print(f"Rows & Column\n {df.shape}")

Rows & Column
 (5000, 11)

In [41]:
print("Columns Statistics")
df.describe()

Columns Statistics

               age    loan_amount  missed_payments
count  4882.000000    4941.000000       5000.00000
mean     40.202991  433029.115968          2.52240
std      11.223237  219088.605102          1.69696
min      21.000000   52928.000000          0.00000
25%      31.000000  229243.000000          1.00000
50%      40.000000  451914.000000          3.00000
75%      50.000000  609863.000000          4.00000
max      59.000000  798423.000000          5.00000

In [43]:
print("Data types\n")
df.info()

Data types

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        5000 non-null   object
 1   age                4882 non-null   float64
 2   income             5000 non-null   object
 3   employment_status  3960 non-null   object
 4   loan_amount        4941 non-null   float64
 5   loan_type          5000 non-null   object
 6   credit_score       4981 non-null   object
 7   missed_payments    5000 non-null   int64
 8   last_payment_date  5000 non-null   object
 9   account_status     5000 non-null   object
 10  region             5000 non-null   object
dtypes: float64(2), int64(1), object(8)
memory usage: 429.8+ KB

In [115]:
print(f'Nulls in each column\n {df.isnull().sum()}')

Nulls in each column
 customer_id                0
age                        0
income                     0
employment_status          0
loan_amount                0
loan_type                  0
credit_score               0
missed_payments            0
last_payment_date          0
account_status             0
region                     0
risk_category              0
days_since_last_payment    0
income_group               0
dtype: int64

Cleaning Dataset

In [62]:
#fixing income
df['income'] = pd.to_numeric(df['income'], errors='coerce')

In [64]:
#fixing credit score
df['credit_score'] = pd.to_numeric(df['credit_score'], errors='coerce')

In [66]:
#fixing date
df['last_payment_date'] = pd.to_datetime(df['last_payment_date'], errors='coerce')

In [68]:
#fixing mising values
df.loc[:,'age'] = df['age'].fillna(df['age'].median())
df.loc[:,'loan_amount'] = df['loan_amount'].fillna(df['loan_amount'].median())
df.loc[:,'income'] = df['income'].fillna(df['income'].median())
df.loc[:,'credit_score'] = df['credit_score'].fillna(df['credit_score'].median())

In [79]:
#fixing categorical column
df['employment_status'] = df['employment_status'].fillna('Unkbown')

Feature Engineering

In [91]:
df['risk_category'] = df['credit_score'].apply(lambda x: "High Risk" if x < 650 else("Medium Risk" if x < 700 else "Low Risk"))

In [93]:
today = pd.to_datetime('today')
df['days_since_last_payment'] = (today - df['last_payment_date']).dt.days

In [100]:
df['income_group'] = pd.cut(df['income'],
                            bins=[0,40000,80000,120000,200000],
                            labels=['Low','Low-Mid','Upper-Mid','High'])

Final Review

In [111]:
print('Data Types\n')
df.info()

Data Types

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              5000 non-null   object
 1   age                      5000 non-null   float64
 2   income                   5000 non-null   float64
 3   employment_status        5000 non-null   object
 4   loan_amount              5000 non-null   float64
 5   loan_type                5000 non-null   object
 6   credit_score             5000 non-null   float64
 7   missed_payments          5000 non-null   int64
 8   last_payment_date        5000 non-null   datetime64[ns]
 9   account_status           5000 non-null   object
 10  region                   5000 non-null   object
 11  risk_category            5000 non-null   object
 12  days_since_last_payment  5000 non-null   int64
 13  income_group             5000 non-null   category
dtypes: category(1), datetime64[ns](1), float64(4), int64(2), object(6)
memory usage: 513.0+ KB

In [113]:
print('Nulls in Dataset')
df.isnull().sum()

Nulls in Dataset

customer_id                0
age                        0
income                     0
employment_status          0
loan_amount                0
loan_type                  0
credit_score               0
missed_payments            0
last_payment_date          0
account_status             0
region                     0
risk_category              0
days_since_last_payment    0
income_group               0
dtype: int64

Data Export

In [120]:
print('Data  Exported successfully')
df.to_csv(r'C:\Users\navee\OneDrive\Desktop\HR ANALYTICS\Credit Risk & Rating Analysis\credit_risk_cleaned.csv', index=False)

Data  Exported successfully